### ISSUE TITLE
[Feature] Frequency of update setting

### ISSUE THREAD

**Issue by Adrian57** [dobrishinov/PowerLinkESP#1]
Firstly, FANTASTIC project. It works a treat. LOVE IT! Thank you.

It would be fantastic to have an Update Frequency setting.

If, for example, you were monitoring a voltage over a long time, perhaps a few hours, there would be an awful lot of data points. It would be great to be able to set an update frequency in such a case - to perhaps 60 seconds and then set a number of hours for the History Range.

**Comment by dobrishinov** [comment]
> Firstly, FANTASTIC project. It works a treat. LOVE IT! Thank you.
> 
> It would be fantastic to have an Update Frequency setting.
> 
> If, for example, you were monitoring a voltage over a long time, perhaps a few hours, there would be an awful lot of data points. It would be great to be able to set an update frequency in such a case - to perhaps 60 seconds and then set a number of hours for the History Range.

Hey, this is a good suggestion! 
The feature is implemented here 😊 - https://github.com/dobrishinov/PowerLinkESP/commit/ed054fe87719d8dcca5c24c02cc7f784af692059

Please don't hesitate to report bugs if you find them!

Regards!
